### ISSUE TITLE
Could you update this project to Processing3?

### ISSUE THREAD

**Issue by q2dg** [pardo-bsso/processing-arduino#1]
Thanks a lot!

**Comment by pardo-bsso** [comment]
Hi @q2dg  , I'll give it a look over the weekend. I'll be surprised if there isn't a more up to date version of this.

**Comment by pardo-bsso** [comment]
@q2dg 
I do not have with me an install of Processing 3 but how does it fail there?

Does this library work: https://github.com/firmata/processing ?

Besides, if you are not tied to Firmata, OSC is a nice alternative ( using oscP5 + oscduino or equivalents)

**Comment by q2dg** [comment]
Thanks for your answer.
OSC seems pretty abandoned...(http://www.sojamo.de/libraries/oscP5)
I haven't tried...maybe anything fails, but I wanted to be sure this repository is up to date. My intention only was pointing up on this necessary maintenance. In fact, I will open the same issue on https://github.com/firmata/processing  because I've just read last commit was from two years ago...
Thanks!

**Comment by pardo-bsso** [comment]
Yes, seems so.
The project I used this on is long gone but if there's interest I'll keep
it more or less up to date.

**Comment by q2dg** [comment]
Thanks a lot
I'll close the issue, then
